apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: twchallenge.ddns.net
    http:
      paths:
      - path: /
        backend:
          serviceName: app-service
          servicePort: 80